version: '3.7'

services:
    springboot:
      #image: 10.50.23.30:5000/boot-vms:latest ### Edit image name 
      image: 10.50.23.30:5000/appname-was:latest ### Edit image name 
      build:
        context: .
        dockerfile: Dockerfile
#      restart: always # if container down restart autometic
      user: "701" # Fixed Value (asmanager)
#      user: root
      ports:
        - 8580:8080 ### Edit port name (http) 
        - 8509:8009 ### Edit port name (ajp)
        - 10490:9990 ### Edit port name (webadmin)
      deploy:
        mode: replicated
        replicas: 1
        placement:
#          constraints: [node.role == manager]
#          constraints: [node.role == worker]
#          constraints: [node.role != manager]
           constraints: [node.hostname == jv0516]

      volumes:
        - /box/logs/appname/springboot:/box/java_logs/appname ### Edit WAS name , application log dir
#      networks:
#        - backend
      environment:
        WAS_NAME: appname ### Edit WAS name 
        TZ: Asia/Seoul

