version: '3.7'

services:
    wildfly:
      image: 10.50.23.30:5000/wildfly14-common:latest ### Edit image name 
      build:
        context: .
        dockerfile: Dockerfile
#      restart: always # if container down restart autometic
      user: root
      ports:
        - 8083:8080 ### Edit port name 
        - 9994:9990 ### Edit port name 
      deploy:
        mode: replicated
        replicas: 2
      volumes:
        - /box/logs/wildfly/scouter_dashboard:/opt/jboss/wildfly/standalone/log ### Edit WAS name 
#      networks:
#        - backend
      environment:
        WAS_NAME: scouter_dashboard ### Edit WAS name 
        TZ: Asia/Seoul

