version: '3.7'

services:
    springboot:
      #image: 10.50.23.30:5000/boot-vms:latest ### Edit image name 
      image: 10.50.23.30:5000/vms-was:latest ### Edit image name 
      build:
        context: .
        dockerfile: Dockerfile
#      restart: always # if container down restart autometic
#      user: "701"
#      user: root
      ports:
        - 8180:8080 ### Edit port name (http) 
        - 8109:8009 ### Edit port name (ajp)
        - 10090:9990 ### Edit port name (webadmin)
      deploy:
        mode: replicated
        replicas: 1
        placement:
#          constraints: [node.role == manager]
          constraints: [node.role == worker]
#           constraints: [node.hostname == jv0516]

      volumes:
        - /box/logs/vms/springboot:/box/java_logs/vms ### Edit WAS name 
#      networks:
#        - backend
      environment:
        WAS_NAME: vms ### Edit WAS name 
        TZ: Asia/Seoul

