version: '3.7'

services:
    wildfly:
      container_name: wildfly
      image: wildfly14-common
      restart: always # if container down restart autometic
      user: root
      ports:
        - 8080:8080
        - 9990:9990
      volumes:
         - /box/logs/wildfly:/opt/jboss/wildfly/standalone/log

#networks:
#    default:
#      external:
#        name: devops
