version: '3.7'

services:
    wildfly:
      container_name: ${WAS_NAME}_wildfly
      image: wildfly14-common:v.0.1
#      restart: always # if container down restart autometic
      user: root
      ports:
        - ${HTTP_PORT}:8080
        - ${ADMIN_PORT}:9990
      volumes:
        - /box/logs/wildfly/${WAS_NAME}:/opt/jboss/wildfly/standalone/log
#      networks:
#        - backend
      environment:
        SERVER_NAME: ${WAS_NAME}
        TZ: Asia/Seoul
