version: '3.7'

services:
    wildfly:
      container_name: scouter_dashboard_wildfly
      image: 10.50.23.30:5000/wildfly14-common:latest
      build:
        context: .
        dockerfile: Dockerfile
#      restart: always # if container down restart autometic
#      user: root
      ports:
        - 8083:8080
        - 9994:9990
      deploy:
        mode: replicated
        replicas: 2
#      volumes:
#        - /box/logs/wildfly/${WAS_NAME}:/opt/jboss/wildfly/standalone/log
#      networks:
#        - backend
      environment:
        WAS_NAME: scouter_dashboard
        TZ: Asia/Seoul

