version: '3.7'

services:
    springboot:
      #image: 10.50.23.30:5000/boot-vms:latest ### Edit image name 
      image: %REGISTRY%/%APPLICATION_NAME%:latest ### Edit image name 
      build:
        context: .
        dockerfile: Dockerfile
#      restart: always # if container down restart autometic
      user: "701" # Fixed Value (asmanager)
#      user: root
#      ports:
#        - %HTTP_PORT%:8080 ### Edit port name (http) 
#        - %AJP_PORT%:8009 ### Edit port name (ajp)
#        - %ADMIN_PORT%:9990 ### Edit port name (webadmin)
      deploy:
        mode: replicated
        replicas: 2
        placement:
#          constraints: [node.role == manager]
#          constraints: [node.role == worker]
          constraints: [node.role != manager]
#           constraints: [node.hostname == jv0516]

#      volumes:
#        - /box/logs/%APPLICATION_NAME%/springboot:/box/java_logs/%APPLICATION_NAME% ### Edit WAS name , application log dir
#      networks:
#        - backend
      networks:
       - backend 
      environment:
        TZ: Asia/Seoul
networks:
  backend:
    driver: overlay
        