version: '3.7'

services:
    wildfly:
      image: 10.50.23.30:5000/wildfly14-common:latest ### Edit image name 
      build:
        context: .
        dockerfile: Dockerfile
#      restart: always # if container down restart autometic
      user: "701"
      ports:
        - 8380:8080 ### Edit port name (http) 
        - 8039:8009 ### Edit port name (ajp)
        - 10290:9990 ### Edit port name (webadmin)
      deploy:
        mode: replicated
        replicas: 2
      volumes:
        - /box/logs/wildfly/scouter_dashboard:/opt/jboss/wildfly/standalone/log ### Edit WAS name 
#      networks:
#        - backend
      environment:
        WAS_NAME: scouter_dashboard ### Edit WAS name 
        TZ: Asia/Seoul

